
export default new Map([
["src/content/docs/guides/utilidades.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Futilidades.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/install.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Finstall.mdx&astroContentModuleFlag=true")],
["src/content/docs/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/cosas/asides.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fcosas%2Fasides.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/cosas/cards.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fcosas%2Fcards.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/cosas/badges.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fcosas%2Fbadges.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/cosas/card-grids.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fcosas%2Fcard-grids.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/cosas/code.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fcosas%2Fcode.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/cosas/file-tree.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fcosas%2Ffile-tree.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/cosas/icons.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fcosas%2Ficons.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/cosas/link-buttons.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fcosas%2Flink-buttons.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/cosas/link-cards.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fcosas%2Flink-cards.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/cosas/steps.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fcosas%2Fsteps.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/cosas/tabs.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fcosas%2Ftabs.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/cosas/using-components.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fcosas%2Fusing-components.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/commands/cat.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fcommands%2Fcat.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/commands/disc-info.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fcommands%2Fdisc-info.mdx&astroContentModuleFlag=true")]]);
		